# Auto-generate K8s and GitOps configuration manifests with Terraform outputs
# This eliminates manual placeholder replacements of EKS roles, account IDs, and Repo URLs.

resource "local_file" "gitops_app_of_apps" {
  filename = "${path.module}/../../../gitops/app-of-apps.yaml"
  content  = <<EOT
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: '${var.git_repo_url}'
    targetRevision: HEAD
    path: infrastructure/gitops/apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
EOT
}

resource "local_file" "gitops_mediguide_application" {
  filename = "${path.module}/../../../gitops/mediguide-application.yaml"
  content  = <<EOT
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mediguide-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: '${var.git_repo_url}'
    targetRevision: HEAD
    path: infrastructure/k8s/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ${var.project_name}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
EOT
}

resource "local_file" "gitops_apps_mediguide_app" {
  filename = "${path.module}/../../../gitops/apps/mediguide-app.yaml"
  content  = <<EOT
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mediguide-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: '${var.git_repo_url}'
    targetRevision: HEAD
    path: infrastructure/k8s/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ${var.project_name}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
EOT
}

resource "local_file" "gitops_apps_aws_load_balancer" {
  filename = "${path.module}/../../../gitops/apps/aws-load-balancer-controller.yaml"
  content  = <<EOT
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://aws.github.io/eks-charts'
    chart: aws-load-balancer-controller
    targetRevision: 1.6.2
    helm:
      parameters:
        - name: clusterName
          value: ${var.project_name}
        - name: serviceAccount.create
          value: 'true'
        - name: serviceAccount.name
          value: aws-load-balancer-controller
        - name: 'serviceAccount.annotations.eks\.amazonaws\.com/role-arn'
          value: ${module.irsa_alb.role_arn}
        - name: vpcId
          value: ${module.vpc.vpc_id}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
EOT
}

resource "local_file" "k8s_kustomization_prod" {
  filename = "${path.module}/../../../k8s/overlays/prod/kustomization.yaml"
  content  = <<EOT
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - external-secret.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml

# Patch base ServiceAccount to bind it to the EKS IRSA role ARN generated by Terraform
patches:
  - target:
      kind: ServiceAccount
      name: mediguide-sa
    patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: mediguide-sa
        annotations:
          eks.amazonaws.com/role-arn: "${module.irsa_eso.role_arn}"
EOT
}
