apiVersion: v1
kind: ConfigMap
metadata:
  name: mediguide-config
  namespace: mediguide
data:
  PORT: "5000"
  NODE_ENV: "production"
  ALLOWED_ORIGIN: "http://localhost:5000"
  GROQ_MODEL: "llama-3.3-70b-versatile"
  PRIMARY_PROVIDER: "groq"
