apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://aws.github.io/eks-charts'
    chart: aws-load-balancer-controller
    targetRevision: 1.6.2
    helm:
      parameters:
        - name: clusterName
          value: mediguide
        - name: serviceAccount.create
          value: 'true'
        - name: serviceAccount.name
          value: aws-load-balancer-controller
        - name: 'serviceAccount.annotations.eks\.amazonaws\.com/role-arn'
          value: arn:aws:iam::584860296807:role/mediguide-alb-controller
        - name: vpcId
          value: vpc-0c1b847e60335ea7a
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
